// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4aBwSTn8XdhWdZZwS5s8zMIBFK0Kt8Hk',
    appId: '1:818627473764:web:d86353b5b1060d038a0a71',
    messagingSenderId: '818627473764',
    projectId: 'e-rationshop',
    authDomain: 'e-rationshop.firebaseapp.com',
    storageBucket: 'e-rationshop.firebasestorage.app',
    measurementId: 'G-6FEYW40YPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqdNV4D7N6eNyz6KNryh1BOs0kwACSHSM',
    appId: '1:818627473764:android:87cf58263fe142d18a0a71',
    messagingSenderId: '818627473764',
    projectId: 'e-rationshop',
    storageBucket: 'e-rationshop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUtEFtPXXOkCGdpNC0iMbbKXiMejOpizU',
    appId: '1:818627473764:ios:0715d887753233d48a0a71',
    messagingSenderId: '818627473764',
    projectId: 'e-rationshop',
    storageBucket: 'e-rationshop.firebasestorage.app',
    iosBundleId: 'com.example.erationshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUtEFtPXXOkCGdpNC0iMbbKXiMejOpizU',
    appId: '1:818627473764:ios:0715d887753233d48a0a71',
    messagingSenderId: '818627473764',
    projectId: 'e-rationshop',
    storageBucket: 'e-rationshop.firebasestorage.app',
    iosBundleId: 'com.example.erationshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4aBwSTn8XdhWdZZwS5s8zMIBFK0Kt8Hk',
    appId: '1:818627473764:web:daa563a1c797532a8a0a71',
    messagingSenderId: '818627473764',
    projectId: 'e-rationshop',
    authDomain: 'e-rationshop.firebaseapp.com',
    storageBucket: 'e-rationshop.firebasestorage.app',
    measurementId: 'G-95V0EDYP8H',
  );
}
